version: "3"

env:
  DAY: 6
  PART: 1

tasks:
  aoc2022:
    desc: Run Advent of Code 2022
    cmds:
      - go run ./cmd/aoc2022

  aoc2023:
    desc: Run Advent of Code 2023
    cmds:
      - go run ./cmd/aoc2023
