version: "3"
env:
  AOC_SESSION: "{{.AOC_SESSION}}"
  AOC_YEAR: "{{.AOC_YEAR}}"
  AOC_DAY: "{{.AOC_DAY}}"
  AOC_PART: "{{.AOC_PART}}"
tasks:
  day:
    desc: Increment day
    cmds:
      - sed -i -e "s/AOC_PART=.*/AOC_PART=1/; s/AOC_DAY=.*/AOC_DAY=$((AOC_DAY+1))/" .envrc
      - direnv allow
  part:
    desc: Increment part
    cmds:
      - sed -i -e "s/AOC_PART=.*/AOC_PART=$((AOC_PART+1))/" .envrc
      - direnv allow

  get:
    desc: Get today's data
    cmds:
      - go run . -y $AOC_YEAR -d $AOC_DAY -p $AOC_PART -g
      - echo "you must manaully populate the example input data"
  default:
    desc: Run Advent of Code (make sure to run get for the day)
    cmds:
      - go run . -y $AOC_YEAR -d $AOC_DAY -p $AOC_PART
  test:
    desc: Run tests
    cmds:
      - go run . -y $AOC_YEAR -d $AOC_DAY -p $AOC_PART -t
